name: jaspr_daisyui
description: Tailwind and DaisyUI integration for Jaspr.
version: 0.1.0
repository: https://github.com/dazemc/jaspr_daisyui
issue_tracker: https://github.com/dazemc/jaspr_daisyui
documentation: https://docs.jaspr.site/eco/tailwind

topics:
  - jaspr
  - web
  - html
  - css

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.0.0
  build_modules: ^5.0.4
  glob: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.0
  lints: any
